# Generated by Django 5.0.1 on 2024-02-05 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sydney_participant', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.FloatField()),
                ('participant', models.IntegerField()),
                ('student_score', models.IntegerField()),
                ('year_lvl_name', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=1)),
                ('correct_answer', models.CharField(max_length=1)),
                ('question', models.IntegerField()),
                ('assesment_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.assessmentarea')),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.award')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.class')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.school')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.subject')),
            ],
        ),
    ]
