# Generated by Django 5.0.1 on 2024-02-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='award',
            new_name='name',
        ),
    ]
