# Generated by Django 5.0.1 on 2024-02-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_rename_cls_name_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_name',
            new_name='name',
        ),
    ]
